FROM osrf/ros:noetic-desktop-full

RUN apt-get update && apt-get install -y \
    ros-noetic-ackermann-msgs \
    ros-noetic-geometry2 \
    ros-noetic-hector-gazebo \
    ros-noetic-hector-models \
    ros-noetic-jsk-rviz-plugins \
    ros-noetic-ros-control \
    ros-noetic-ros-controllers \
    ros-noetic-velodyne-simulator

# Set up workspace
RUN mkdir -p /root/gem_ws/src
WORKDIR /root/gem_ws/src
COPY . /root/gem_ws/src

WORKDIR /root/gem_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"

CMD ["bash"]
